Repository CSC207-2022F-UofT/course-project-32-things-to-do, pull requests merged in 2022-12, with the labels that each got.

#67 User registration & log in
  src/main/java/Main.java
  src/main/java/data/users.ser
  src/main/java/entities/GeneralUserFactory.java
  src/main/java/entities/InstructorUserFactory.java
  src/main/java/entities/StudentUser.java
  src/main/java/entities/StudentUserFactory.java
  src/main/java/entities/UserFactory.java
  src/main/java/screens/InstructorMain.java
  src/main/java/screens/StudentMainScreen.java
  src/main/java/screens/login_registration/FileUser.java
  src/main/java/screens/login_registration/InMemoryUser.java
  src/main/java/screens/login_registration/LoginScreen.java
  src/main/java/screens/login_registration/LogoutResponseFormatter.java
  src/main/java/screens/login_registration/RegisterScreen.java
  src/main/java/use_cases/login_registration/login_usecase/LoginInteractor.java
  src/main/java/use_cases/login_registration/login_usecase/LoginRequestModel.java
  src/main/java/use_cases/login_registration/login_usecase/LoginResponseModel.java
  src/main/java/use_cases/login_registration/logout_usecase/LogoutInteractor.java
  src/main/java/use_cases/login_registration/logout_usecase/LogoutPresenter.java
  src/main/java/use_cases/login_registration/user_register_usecase/InstructorSaveRequest.java
  src/main/java/use_cases/login_registration/user_register_usecase/StudentSaveRequest.java
  src/main/java/use_cases/login_registration/user_register_usecase/UserRegInteractor.java
  src/main/java/use_cases/login_registration/user_register_usecase/UserRegRequest.java
  src/main/java/use_cases/login_registration/user_register_usecase/UserRegSaveRequest.java
  src/main/java/users
  src/test/java/FileUserTest.java
  src/test/java/data/userstest.ser
  src/test/java/entities/UserFactoryTest.java
  src/test/java/entities/UserUnitTest.java
  src/test/java/login_usecase/LoginInteractorTest.java
  src/test/java/logout_usecase/LogoutInteractorTest.java
  src/test/java/user_register_usecase/UserRegInteractorTest.java
  src/test/java/user_register_usecase/UserRegRequestTest.java
  src/test/java/user_register_usecase/UserRegSaveRequestTest.java
Labels: enhancement, tests, code style / organization

#69 New current user entity to track logged-in user
  src/main/java/Main.java
  src/main/java/entities/CurrentUser.java
  src/main/java/screens/InstructorMainScreen.java
  src/main/java/screens/calendar_scheduler/CalendarScreen.java
  src/main/java/screens/collaborative_task_scheduling/ScheduleCTScreen.java
  src/main/java/screens/collaborative_task_scheduling/ScheduleCTView.java
  src/main/java/screens/courses_features/CourseCreationScreen.java
  src/main/java/screens/login_registration/LoginScreen.java
  src/main/java/screens/login_registration/RegisterScreen.java
  src/main/java/screens/task_management/event_creation_screens/EventCreationScreen.java
  src/main/java/use_cases/login_registration/login_usecase/LoginInteractor.java
  src/main/java/use_cases/login_registration/user_register_usecase/UserRegInteractor.java
Labels: bug, code style / organization

#54 Feature 7 debugging + feature refinement
  src/main/java/Main.java
  src/main/java/data/TaskMap
  src/main/java/data/TaskMap.txt
  src/main/java/data/users.ser
  src/main/java/entities/Course.java
  src/main/java/entities/CourseMap.java
  src/main/java/screens/course_features/CourseCreationController.java
  src/main/java/screens/course_features/CourseCreationFailed.java
  src/main/java/screens/course_features/CourseCreationPresenter.java
  src/main/java/screens/course_features/CourseCreationScreen.java
  src/main/java/screens/course_features/CourseEnrolmentController.java
  src/main/java/screens/course_features/CourseEnrolmentFailed.java
  src/main/java/screens/course_features/CourseEnrolmentPresenter.java
  src/main/java/screens/course_features/CourseEnrolmentScreen.java
  src/main/java/screens/course_features/CourseFoundScreen.java
  src/main/java/screens/course_features/FileCourse.java
  src/main/java/screens/course_features/InMemoryCourse.java
  src/main/java/screens/courses_features/CourseFoundScreen.java
  src/main/java/screens/courses_features/FileCourse.java
  src/main/java/screens/courses_features/InMemoryCourse.java
  src/main/java/screens/login_registration/FileUser.java
  src/main/java/use_cases/course_features/course_creation_use_case/CourseCreationDsGateway.java
  src/main/java/use_cases/course_features/course_creation_use_case/CourseCreationInteractor.java
  src/main/java/use_cases/course_features/course_creation_use_case/CourseCreationOutputBoundary.java
  src/main/java/use_cases/course_features/course_creation_use_case/CourseCreationRequestModel.java
  src/main/java/use_cases/course_features/course_creation_use_case/CourseCreationResponseModel.java
  src/main/java/use_cases/course_features/course_creation_use_case/CourseCreationSaveRequest.java
  src/main/java/use_cases/course_features/course_enrolment_use_case/CourseEnrolmentDsGateway.java
  src/main/java/use_cases/course_features/course_enrolment_use_case/CourseEnrolmentInputBoundary.java
  src/main/java/use_cases/course_features/course_enrolment_use_case/CourseEnrolmentInteractor.java
  src/main/java/use_cases/course_features/course_enrolment_use_case/CourseEnrolmentOutputBoundary.java
  src/main/java/use_cases/course_features/course_enrolment_use_case/CourseEnrolmentRequestModel.java
  src/main/java/use_cases/course_features/course_enrolment_use_case/CourseEnrolmentResponseModel.java
  src/main/java/use_cases/course_features/course_enrolment_use_case/CourseTasksToStudentTodolistDsGateway.java
  src/main/java/use_cases/login_registration/user_register_usecase/UserRegSaveRequest.java
  src/main/java/users
  src/test/java/FileUserTest.java
  src/test/java/data/userstest.ser
  src/test/java/test_course_features/CourseCreationInteractorTest.java
  src/test/java/test_course_features/CourseEnrolmentInteractorTest.java
  src/test/java/test_entities/CourseUnitTest.java
Labels: bug, enhancement, code style / organization

#73 Feature 5 - tests, functionality, readme
  README.md
  images/scheduling_ct.png
  src/main/java/Main.java
  src/main/java/data/TaskMap
  src/main/java/data/users
  src/main/java/data/users.ser
  src/main/java/screens/collaborative_task_scheduling/ScheduleCTController.java
  src/main/java/screens/collaborative_task_scheduling/ScheduleCTFormatter.java
  src/main/java/screens/collaborative_task_scheduling/ScheduleCTPresenter.java
  src/main/java/screens/collaborative_task_scheduling/ScheduleCTScreen.java
  src/main/java/screens/collaborative_task_scheduling/ScheduleCTView.java
  src/main/java/screens/collaborative_task_scheduling/ScheduleCTViewInterface.java
  src/main/java/use_cases/collaborative_task_scheduling/scheduling_ct_use_case/ScheduleCTInputBoundary.java
  src/main/java/use_cases/collaborative_task_scheduling/scheduling_ct_use_case/ScheduleCTInteractor.java
  src/main/java/use_cases/collaborative_task_scheduling/scheduling_ct_use_case/ScheduleCTRequestModel.java
  src/main/java/use_cases/collaborative_task_scheduling/scheduling_ct_use_case/ScheduleCTResponseModel.java
  src/main/java/users
  src/test/java/data/userstest.ser
  src/test/java/scheduling_ct_use_case/ScheduleCTInteractorTest.java
  src/test/java/scheduling_ct_use_case/ScheduleCTInteractorUnitTest.java
  src/test/java/scheduling_ct_use_case/ScheduleCTRequestModelTest.java
  src/test/java/scheduling_ct_use_case/ScheduleCTResponseModelTest.java
Labels: tests, code style / organization

#77 Feature 6 updates
  src/main/java/Main.java
  src/main/java/screens/course_features/InMemoryCourse.java
  src/main/java/screens/course_progress/ProgressTrackerController.java
  src/main/java/screens/course_progress/ProgressTrackerPresenter.java
  src/main/java/screens/course_progress/ProgressTrackerScreen.java
  src/main/java/screens/course_tracker/GradeCalculatorController.java
  src/main/java/screens/course_tracker/GradeCalculatorPresenter.java
  src/main/java/screens/course_tracker/GradeCalculatorViewBoundary.java
  src/main/java/screens/course_tracker/GradeCalculatorViewModel.java
  src/main/java/screens/course_tracker/ProgressTrackerController.java
  src/main/java/screens/course_tracker/ProgressTrackerPresenter.java
  src/main/java/screens/course_tracker/ProgressTrackerScreen.java
  src/main/java/screens/course_tracker/ProgressTrackerViewBoundary.java
  src/main/java/screens/course_tracker/ProgressTrackerViewModel.java
  src/main/java/screens/course_tracker/ProgressTrackingFail.java
  src/main/java/screens/task_management/todolist_screens/ToDoListFail.java
  src/main/java/use_cases/course_tracker/CourseTrackerInteractor.java
  src/main/java/use_cases/course_tracker/grade_calculator_use_case/GradeCalculatorInputBoundary.java
  src/main/java/use_cases/course_tracker/grade_calculator_use_case/GradeCalculatorInteractor.java
  src/main/java/use_cases/course_tracker/grade_calculator_use_case/GradeCalculatorOutputBoundary.java
  src/main/java/use_cases/course_tracker/grade_calculator_use_case/GradeCalculatorRequestModel.java
  src/main/java/use_cases/course_tracker/grade_calculator_use_case/GradeCalculatorResponseModel.java
  src/main/java/use_cases/course_tracker/progress_tracker_use_case/ProgressTrackerInputBoundary.java
  src/main/java/use_cases/course_tracker/progress_tracker_use_case/ProgressTrackerInteractor.java
  src/main/java/use_cases/course_tracker/progress_tracker_use_case/ProgressTrackerOutputBoundary.java
  src/main/java/use_cases/course_tracker/progress_tracker_use_case/ProgressTrackerRequestModel.java
  src/main/java/use_cases/course_tracker/progress_tracker_use_case/ProgressTrackerResponseModel.java
  src/test/java/course_tracker_use_cases/GradeCalculatorTest.java
  src/test/java/course_tracker_use_cases/ProgressTrackerTest.java
  src/test/java/progress_tracker_use_case/ProgressTrackerTest.java
Labels: bug, documentation, enhancement, code style / organization

#76 Feature 2 - README updates, slight improvements
  README.md
  images/assignment_edit_delete.png
  images/event_creation.png
  images/event_edit_delete.png
  images/instructor_choose_task.png
  images/student_assignment_creation.png
  images/student_choose_task.png
  images/student_test_creation.png
  images/test_edit_delete.png
  images/todo_list_screen.png
  src/main/java/screens/task_management/task_creation_screens/StudentChooseTaskCreateScreen.java
  src/main/java/screens/task_management/task_creation_screens/assignment_creation_screens/StudentAssignmentCreationScreen.java
  src/main/java/screens/task_management/task_creation_screens/event_creation_screens/EventCreationScreen.java
  src/main/java/screens/task_management/task_creation_screens/test_creation_screens/InstructorTestCreationScreen.java
  src/main/java/screens/task_management/task_creation_screens/test_creation_screens/StudentTestCreationScreen.java
  src/main/java/screens/task_management/task_edit_delete_screens/assignment_edit_delete_screens/AssignmentEditDeleteScreen.java
  src/main/java/screens/task_management/task_edit_delete_screens/event_edit_delete_screens/EventEditDeleteScreen.java
  src/main/java/screens/task_management/task_edit_delete_screens/test_edit_delete_screens/TestEditDeleteScreen.java
Labels: documentation, code style / organization

#74 Major Update and Fixes for Scheduling Feature
  README.md
  src/main/java/Main.java
  src/main/java/screens/calendar_scheduler/CalendarScreen.java
  src/main/java/screens/calendar_scheduler/DayViewPanel.java
  src/main/java/screens/calendar_scheduler/ScheduleConflictPresenter.java
  src/main/java/screens/calendar_scheduler/SchedulerResponseFormatter.java
  src/main/java/screens/calendar_scheduler/WeekViewPanel.java
  src/main/java/screens/task_management/task_creation_screens/StudentChooseTaskCreateScreen.java
  src/main/java/screens/task_management/todolist_screens/ToDoListScreen.java
  src/main/java/use_cases/calendar_scheduler/schedule_conflict_use_case/ScheduleConflictOutputBoundary.java
  src/main/java/use_cases/calendar_scheduler/schedule_conflict_use_case/ScheduleConflictResponseModel.java
  src/main/java/use_cases/calendar_scheduler/scheduler_use_case/SchedulerController.java
  src/main/java/use_cases/calendar_scheduler/scheduler_use_case/SchedulerInteractor.java
  src/main/java/use_cases/calendar_scheduler/scheduler_use_case/SchedulerPresenter.java
  src/main/java/use_cases/calendar_scheduler/scheduler_use_case/SchedulerRequestModel.java
  src/main/java/use_cases/calendar_scheduler/scheduler_use_case/SchedulerResponseModel.java
  src/main/java/use_cases/task_management/task_creation_use_case/TaskCreationInteractor.java
  src/main/java/use_cases/task_management/task_edit_use_case/TaskEditInteractor.java
  src/test/java/scheduler_use_case/SchedulerInteractorTest.java
  src/test/java/use_cases/task_management/task_creation_use_case/TaskCreationInteractorTest.java
  src/test/java/use_cases/task_management/task_edit_use_case/TaskEditInteractorTest.java
Labels: bug, tests, code style / organization

#86 Calendar Screen Clean Architecture bug fix
  src/main/java/Main.java
  src/main/java/screens/StudentMainScreen.java
  src/main/java/screens/calendar_scheduler/CalendarPresenter.java
  src/main/java/screens/calendar_scheduler/CalendarScreen.java
  src/main/java/screens/calendar_scheduler/DayViewPanel.java
  src/main/java/screens/calendar_scheduler/MonthViewPanel.java
  src/main/java/screens/calendar_scheduler/WeekViewPanel.java
  src/main/java/screens/calendar_scheduler/WorkingHoursController.java
  src/main/java/screens/calendar_scheduler/WorkingHoursPresenter.java
  src/main/java/screens/task_management/todolist_screens/ToDoListPresenter.java
  src/main/java/screens/task_management/todolist_screens/ToDoListScreen.java
  src/main/java/use_cases/calendar_scheduler/working_hours_use_case/WorkingHoursInputBoundary.java
  src/main/java/use_cases/calendar_scheduler/working_hours_use_case/WorkingHoursInteractor.java
  src/main/java/use_cases/calendar_scheduler/working_hours_use_case/WorkingHoursOutputBoundary.java
  src/main/java/use_cases/calendar_scheduler/working_hours_use_case/WorkingHoursRequestModel.java
  src/main/java/use_cases/calendar_scheduler/working_hours_use_case/WorkingHoursResponseModel.java
  src/main/java/use_cases/task_management/todolist_use_case/ToDoListInteractor.java
  src/main/java/use_cases/task_management/todolist_use_case/ToDoListItem.java
  src/test/java/calendar_scheduler_use_case/SchedulerInteractorTest.java
  src/test/java/calendar_scheduler_use_case/WorkingHoursInteractorTest.java
Labels: (de)bug

#97 General bug fixes for scheduling use case
  src/main/java/screens/calendar_scheduler/MonthViewPanel.java
  src/main/java/use_cases/calendar_scheduler/scheduler_use_case/SchedulerInteractor.java
  src/main/java/use_cases/task_management/task_creation_use_case/TaskCreationInteractor.java
  src/test/java/test_task_management/test_task_edit/TaskEditInteractorTest.java
Labels: (de)bug

#95 Added Screens and all Use Cases for Invitation + Collaborative Task
  README.md
  resources/images/ct_create.png
  resources/images/ct_edit.png
  resources/images/dashboard_screen2.png
  src/main/java/Main.java
  src/main/java/entities/Invitation.java
  src/main/java/screens/StudentMainScreen.java
  src/main/java/screens/collaborative_task_management/collaborative_task_creation_screens/CollaborativeTaskCreateScreen.java
  src/main/java/screens/collaborative_task_management/collaborative_task_creation_screens/CollaborativeTaskCreationController.java
  src/main/java/screens/collaborative_task_management/collaborative_task_creation_screens/CollaborativeTaskCreationFailed.java
  src/main/java/screens/collaborative_task_management/collaborative_task_creation_screens/CollaborativeTaskCreationResponseFormatter.java
  src/main/java/screens/collaborative_task_management/collaborative_task_edit_delete_screens/CollaborativeTaskDeletionController.java
  src/main/java/screens/collaborative_task_management/collaborative_task_edit_delete_screens/CollaborativeTaskDeletionFailed.java
  src/main/java/screens/collaborative_task_management/collaborative_task_edit_delete_screens/CollaborativeTaskDeletionResponseFormatter.java
  src/main/java/screens/collaborative_task_management/collaborative_task_edit_delete_screens/CollaborativeTaskEditController.java
  src/main/java/screens/collaborative_task_management/collaborative_task_edit_delete_screens/CollaborativeTaskEditDeleteScreen.java
  src/main/java/screens/collaborative_task_management/collaborative_task_edit_delete_screens/CollaborativeTaskEditFailed.java
  src/main/java/screens/collaborative_task_management/collaborative_task_edit_delete_screens/CollaborativeTaskEditResponseFormatter.java
  src/main/java/screens/collaborative_task_management/collaborative_task_edit_delete_screens/CollaborativeTaskInfoRetreiver.java
  src/main/java/screens/task_management/todolist_screens/ToDoListPresenter.java
  src/main/java/screens/task_management/todolist_screens/ToDoListScreen.java
  src/main/java/use_cases/collaborative_task_management/collaborative_task_creation_use_case/CollaborativeTaskCreationInputBoundary.java
  src/main/java/use_cases/collaborative_task_management/collaborative_task_creation_use_case/CollaborativeTaskCreationInteractor.java
  src/main/java/use_cases/collaborative_task_management/collaborative_task_creation_use_case/CollaborativeTaskCreationOutputBoundary.java
  src/main/java/use_cases/collaborative_task_management/collaborative_task_creation_use_case/CollaborativeTaskCreationPresenter.java
  src/main/java/use_cases/collaborative_task_management/collaborative_task_creation_use_case/CollaborativeTaskCreationRequestModel.java
  src/main/java/use_cases/collaborative_task_management/collaborative_task_creation_use_case/CollaborativeTaskCreationResponseModel.java
  src/main/java/use_cases/collaborative_task_management/collaborative_task_deletion_use_case/CollaborativeTaskDeletionInputBoundary.java
  src/main/java/use_cases/collaborative_task_management/collaborative_task_deletion_use_case/CollaborativeTaskDeletionInteractor.java
  src/main/java/use_cases/collaborative_task_management/collaborative_task_deletion_use_case/CollaborativeTaskDeletionPresenter.java
  src/main/java/use_cases/collaborative_task_management/collaborative_task_deletion_use_case/CollaborativeTaskDeletionRequestModel.java
  src/main/java/use_cases/collaborative_task_management/collaborative_task_deletion_use_case/CollaborativeTaskDeletionResponseModel.java
  src/main/java/use_cases/collaborative_task_management/collaborative_task_edit_use_case/CollaborativeTaskDisplayer.java
  src/main/java/use_cases/collaborative_task_management/collaborative_task_edit_use_case/CollaborativeTaskEditInputBoundary.java
  src/main/java/use_cases/collaborative_task_management/collaborative_task_edit_use_case/CollaborativeTaskEditInteractor.java
  src/main/java/use_cases/collaborative_task_management/collaborative_task_edit_use_case/CollaborativeTaskEditPresenter.java
  src/main/java/use_cases/collaborative_task_management/collaborative_task_edit_use_case/CollaborativeTaskEditRequestModel.java
  src/main/java/use_cases/collaborative_task_management/collaborative_task_edit_use_case/CollaborativeTaskEditResponseModel.java
  src/main/java/use_cases/invitation_management/invitation_creation_use_case/InvitationCreationInputBoundary.java
  src/main/java/use_cases/invitation_management/invitation_creation_use_case/InvitationCreationInteractor.java
  src/main/java/use_cases/invitation_management/invitation_creation_use_case/InvitationCreationOuputBoundary.java
  src/main/java/use_cases/invitation_management/invitation_creation_use_case/InvitationCreationRequestModel.java
  src/main/java/use_cases/invitation_management/invitation_creation_use_case/InvitationCreationResponseModel.java
  src/main/java/use_cases/invitation_management/invitation_reponse_use_case/InvitationResponseDisplayer.java
  src/main/java/use_cases/invitation_management/invitation_reponse_use_case/InvitationResponseInputBoundary.java
  src/main/java/use_cases/invitation_management/invitation_reponse_use_case/InvitationResponseInteractor.java
  src/main/java/use_cases/invitation_management/invitation_reponse_use_case/InvitationResponsePresenter.java
  src/main/java/use_cases/invitation_management/invitation_reponse_use_case/InvitationResponseRequestModel.java
  src/main/java/use_cases/invitation_management/invitation_reponse_use_case/InvitationResponseResponseModel.java
  src/main/java/use_cases/task_management/todolist_use_case/TaskType.java
  src/main/java/use_cases/task_management/todolist_use_case/ToDoListInteractor.java
  src/test/java/test_collaborative_task_management/CollaborativeTaskCreationInteractorTest.java
  src/test/java/test_collaborative_task_management/CollaborativeTaskCreationRequestModelTest.java
  src/test/java/test_collaborative_task_management/CollaborativeTaskCreationResponseModelTest.java
  src/test/java/test_entities/CollaborativeTaskTest.java
  src/test/java/test_entities/InvitationTest.java
Labels: (de)bug, documentation, enhancement, code style / organization

#99 Feature 6 updates - update to README and small change
  README.md
  src/main/java/use_cases/course_tracker/CourseTrackerInteractor.java
  src/main/java/use_cases/course_tracker/progress_tracker_use_case/ProgressTrackerInteractor.java
  src/test/java/test_course_tracker/GradeCalculatorTest.java
  src/test/java/test_course_tracker/ProgressTrackerTest.java
Labels: (de)bug, documentation

#84 Feature 7 - Tests and README
  README.md
  resources/images/course_creation_empty_screen.png
  resources/images/course_enrolment_sucess.png
  resources/images/creation_exists_msg.png
  resources/images/enrolment_success_message.png
  src/main/java/Main.java
  src/main/java/data/users
  src/main/java/entities/Assignment.java
  src/main/java/entities/Course.java
  src/main/java/entities/TaskMap.java
  src/main/java/entities/Test.java
  src/main/java/screens/course_features/CourseEnrolmentController.java
  src/main/java/screens/course_features/CourseEnrolmentScreen.java
  src/main/java/screens/login_registration/FileUser.java
  src/main/java/screens/task_management/FileTaskMap.java
  src/main/java/screens/task_management/InMemoryTaskMap.java
  src/main/java/screens/task_management/task_creation_screens/assignment_creation_screens/InstructorAssignmentCreationScreen.java
  src/main/java/use_cases/course_features/course_creation_use_case/CourseCreationRequestModel.java
  src/main/java/use_cases/course_features/course_enrolment_use_case/CourseEnrolmentCourseDsGateway.java
  src/main/java/use_cases/course_features/course_enrolment_use_case/CourseEnrolmentInputBoundary.java
  src/main/java/use_cases/course_features/course_enrolment_use_case/CourseEnrolmentInteractor.java
  src/main/java/use_cases/course_features/course_enrolment_use_case/CourseEnrolmentOutputBoundary.java
  src/main/java/use_cases/course_features/course_enrolment_use_case/CourseEnrolmentRequestModel.java
  src/main/java/use_cases/course_features/course_enrolment_use_case/CourseEnrolmentResponseModel.java
  src/main/java/use_cases/course_features/course_enrolment_use_case/CourseEnrolmentUserDsGateway.java
  src/test/java/test_course_features/CourseEnrolmentInteractorTest.java
  src/test/java/test_course_features/test_course_creation/CourseCreationRequestModelTest.java
  src/test/java/test_course_features/test_course_enrolment/CourseEnrolmentInteractorTest.java
  src/test/java/test_course_features/test_course_enrolment/CourseEnrolmentRequestModelTest.java
  src/test/java/test_task_management/test_read_write/FileTaskMapTest.java
Labels: (de)bug, documentation, tests

#102 Tests
  src/test/java/test_collaborative_task_management/CollaborativeTaskCreationInteractorTest.java
  src/test/java/test_collaborative_task_management/CollaborativeTaskCreationRequestModelTest.java
  src/test/java/test_collaborative_task_management/CollaborativeTaskCreationResponseModelTest.java
  src/test/java/test_entities/CollaborativeTaskTest.java
  src/test/java/test_entities/InvitationTest.java
Labels: tests

#109 Final clean up of code
  src/main/java/Main.java
  src/main/java/entities/TaskMap.java
  src/main/java/screens/InstructorMainScreen.java
  src/main/java/screens/collaborative_task_management/collaborative_task_creation_screens/CollaborativeTaskCreationController.java
  src/main/java/screens/collaborative_task_management/collaborative_task_edit_delete_screens/CollaborativeTaskDeletionController.java
  src/main/java/screens/collaborative_task_management/collaborative_task_edit_delete_screens/CollaborativeTaskDeletionResponseFormatter.java
  src/main/java/screens/collaborative_task_management/collaborative_task_edit_delete_screens/CollaborativeTaskEditController.java
  src/main/java/screens/collaborative_task_management/collaborative_task_edit_delete_screens/CollaborativeTaskEditResponseFormatter.java
  src/main/java/screens/collaborative_task_management/collaborative_task_edit_delete_screens/CollaborativeTaskInfoRetreiver.java
  src/main/java/screens/course_features/CourseEnrolmentScreen.java
  src/main/java/screens/login_registration/LogoutFailed.java
  src/main/java/screens/task_management/FileTaskMap.java
  src/main/java/screens/task_management/todolist_screens/ToDoListScreen.java
  src/main/java/use_cases/calendar_scheduler/scheduler_use_case/SchedulerResponseModel.java
  src/main/java/use_cases/collaborative_task_management/collaborative_task_edit_use_case/CollaborativeTaskDisplayer.java
  src/main/java/use_cases/collaborative_task_management/collaborative_task_edit_use_case/CollaborativeTaskEditInteractor.java
  src/main/java/use_cases/course_features/course_creation_use_case/CourseCreationRequestModel.java
  src/main/java/use_cases/course_features/course_enrolment_use_case/CourseEnrolmentUserDsGateway.java
  src/main/java/use_cases/login_registration/logout_usecase/LogoutInteractor.java
  src/main/java/use_cases/login_registration/logout_usecase/LogoutResponseModel.java
  src/main/java/use_cases/login_registration/user_register_usecase/InstructorSaveRequest.java
  src/main/java/use_cases/login_registration/user_register_usecase/StudentSaveRequest.java
  src/main/java/use_cases/login_registration/user_register_usecase/UserRegGateway.java
  src/main/java/use_cases/login_registration/user_register_usecase/UserRegInteractor.java
  src/main/java/use_cases/login_registration/user_register_usecase/UserRegSaveRequest.java
  src/main/java/use_cases/task_management/task_creation_use_case/TaskCreationInteractor.java
  src/main/java/use_cases/task_management/task_edit_use_case/TaskEditInteractor.java
  src/main/java/use_cases/task_management/todolist_use_case/TaskType.java
  src/test/java/test_calendar_scheduler/SchedulerInteractorTest.java
  src/test/java/test_calendar_scheduler/WorkingHoursInteractorTest.java
  src/test/java/test_collaborative_task_management/CollaborativeTaskCreationInteractorTest.java
  src/test/java/test_course_features/test_course_enrolment/CourseEnrolmentInteractorTest.java
  src/test/java/test_course_features/test_course_enrolment/CourseEnrolmentRequestModelTest.java
  src/test/java/test_entities/CollaborativeTaskTest.java
  src/test/java/test_entities/InvitationTest.java
Labels: code style / organization
